version: '3.8'

services:
  postgres:
    container_name: proj_postgres
    image: postgres
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: example1
      PGDATA: /data/postgres
    networks:
      - postgres
    restart: unless-stopped
    stdin_open: true
    tty: true


  cache:
    image: redis:7.2.1-alpine
    container_name: proj_redis
    restart: always
    ports:
      - 6380:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxxkKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

volumes:
  postgres:
    driver: local

  cache:
    driver: local

networks:
  postgres:
    driver: bridge
